-- =====================================================
-- Migration Script: Tạo bảng REVIEWS và REVIEW_IMAGES
-- Ngày tạo: 2026-01-07
-- Tính năng: Đánh giá sản phẩm sau khi thanh toán
-- =====================================================

-- 1. Tạo bảng REVIEWS
CREATE TABLE REVIEWS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    
    -- Quan hệ
    PRODUCT_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    ORDER_ID INT NOT NULL,
    
    -- Nội dung đánh giá
    RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    COMMENT NVARCHAR(MAX),
    
    -- Metadata
    CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME,
    
    -- Foreign keys
    CONSTRAINT FK_REVIEWS_PRODUCT 
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWS_USER 
        FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWS_ORDER 
        FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID) ON DELETE CASCADE,
    
    -- Constraint: Mỗi user chỉ đánh giá 1 lần cho 1 sản phẩm trong 1 đơn hàng
    CONSTRAINT UQ_REVIEWS_USER_PRODUCT_ORDER 
        UNIQUE (USER_ID, PRODUCT_ID, ORDER_ID)
);

-- 2. Tạo bảng REVIEW_IMAGES
CREATE TABLE REVIEW_IMAGES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    REVIEW_ID INT NOT NULL,
    IMAGE_URL NVARCHAR(MAX) NOT NULL,
    DISPLAY_ORDER INT DEFAULT 0,
    
    CONSTRAINT FK_REVIEW_IMAGES_REVIEW 
        FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS(ID) ON DELETE CASCADE
);

-- 3. Tạo indexes để tăng performance
CREATE INDEX IDX_REVIEWS_PRODUCT ON REVIEWS(PRODUCT_ID);
CREATE INDEX IDX_REVIEWS_USER ON REVIEWS(USER_ID);
CREATE INDEX IDX_REVIEWS_ORDER ON REVIEWS(ORDER_ID);
CREATE INDEX IDX_REVIEWS_RATING ON REVIEWS(RATING);
CREATE INDEX IDX_REVIEWS_CREATED_AT ON REVIEWS(CREATED_AT DESC);

CREATE INDEX IDX_REVIEW_IMAGES_REVIEW ON REVIEW_IMAGES(REVIEW_ID);

-- 4. Kiểm tra kết quả
SELECT 'REVIEWS table created' as Status;
SELECT 'REVIEW_IMAGES table created' as Status;

-- 5. Test data (Optional - để test)
-- INSERT INTO REVIEWS (PRODUCT_ID, USER_ID, ORDER_ID, RATING, COMMENT)
-- VALUES (1, 2, 1, 5, N'Sản phẩm rất tốt, đóng gói cẩn thận!');
