-- Cập nhật cột IMAGE_URL để lưu được base64 string dài
USE ShopHubDB;
GO

ALTER TABLE PRODUCTS
ALTER COLUMN IMAGE_URL NVARCHAR(MAX);
GO

-- Kiểm tra kết quả
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUCTS' AND COLUMN_NAME = 'IMAGE_URL';
GO
